### PR TITLE
DEP Use guzzle 7

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/10253

### CODE REVIEW

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
Looking at the [one place we use guzzle in cow](https://github.com/silverstripe/cow/blob/51a34b30e8bff0e806788a1d604650bce4dba6d9/src/Steps/Release/PublishRelease.php#L15), I don't think this change will work.

**Comment by maxime-rainville** [comment]
Looks like Guzzle is only use when doing the actual release publishing, maybe we make a best effort to get it working now and debug any issues we come across when we tag the beta?

**Comment by emteknetnz** [comment]
Opps :-) forgot to change `use Http\Adapter\Guzzle6\Client as GuzzleClient;` to `use Http\Adapter\Guzzle7\Client as GuzzleClient;`

Yes we only use it in one place, the API on the php-http guzzle adapter library is the same

https://github.com/php-http/guzzle6-adapter/blob/master/src/Client.php#L45
https://github.com/php-http/guzzle7-adapter/blob/master/src/Client.php#L41

**Review by maxime-rainville — APPROVED** [review]

**Comment by maxime-rainville** [comment]
Looks good ... we'll just have to remember we made this change when we tag the 4.11 beta.

**Pull request merged**
