### PR TITLE
MAJOR When planning you can now indicate that releases should not be created by default

### PR DESCRIPTION
**Pull request by ScopeyNZ**
Additionally there is now an option on the command to opt-in to automatically releasing.

- `--assume-no-releases` is the new flag for not auto-releasing
- `--release=comma,delimited,composer,packages` is the new option for opting in to auto-releasing modules

### CODE REVIEW

**Comment by robbieaverill** [comment]
I don't really understand why this is needed

**Comment by ScopeyNZ** [comment]
When you plan a release it automatically assumes a release of every module. This is a flag for the opposite functionality. It will assumes no releases.

**Comment by robbieaverill** [comment]
Ah right, that makes sense. Maybe rename the “release” terminology to something else- it confuses me. How about “assume patch versions”

**Comment by robbieaverill** [comment]
Do you still want this? I'm not overly convinced we need it TBH

**Comment by ScopeyNZ** [comment]
Na I'll reopen if I change my mind.

**Pull request closed without merging**
