### PR TITLE
BUG Make check for "BUG" tags case-insensitive

### PR DESCRIPTION
**Pull request by tractorcow**
Changelogs were missing commits such as https://github.com/silverstripe-australia/silverstripe-advancedworkflow/pull/289

### CODE REVIEW

**Comment by tractorcow** [comment]
BUGFUX

**Comment by dhensby** [comment]
What about "fix bug"

**Comment by dhensby** [comment]
or "fixes"

**Comment by tractorcow** [comment]
Yeah those are captured. ;D

**Pull request merged**
