### PR TITLE
NEW Allow defining custom repositories for releases

### PR DESCRIPTION
**Pull request by dhensby**
This is a horrible way to do it imo, but kinda works.

Basically, use `cow release [version] --repository=[link to composer repo]`

### CODE REVIEW

**Comment by tractorcow** [comment]
Good start to an idea... will be keen to see it once it's done. :)

**Comment by tractorcow** [comment]
image

**Comment by dhensby** [comment]
it stands for "fixup" leave me alone :P

**Comment by dhensby** [comment]
OK - I've neatened up the commits :)

At the moment you have to break during the "wait" cycle to go and manually update your satis repo (if you're using one). Perhaps for custom repos the wait will only wait once?

**Comment by tractorcow** [comment]
Hi @dhensby just having a look at this feature. The code looks pretty good, but what would help get this over the line is some documentation on how to use the new feature. Let me know what I can do to help. :)

**Pull request merged**
