### PR TITLE
FIX Make release:translate non destructive

### LINKED ISSUE #202: Make release:translate non destructive
Currently the `release:translate` command will remove any unused source keys 

When `tx push -s` is run, it will delete these unused source values from transifex.  I haven't tested this, though presumably it will also delete any corresponding translations.

**NOTE: It seems that unused source keys are retained, but there are some keys missing in transifex which get removed from the translation yml files.**

This will have an impact on older minor branches, specifically if we run `tx pull` during a patch release on an old minor branch, for instance for a security release.  In this scenario, there will be a translations regression e.g. keys and values in de.yml will be removed.

An unfortunate side effect of this is old irrelevant keys and values will clutter the source en.yml and translation de.yml in the current minor.  That's a trade off we need to take.

### ACs
- [ ] When running `cow release:translate`, unused keys are retained in all .yml and .json translation files

### PRs
- [ ] https://github.com/silverstripe/cow/pull/203

### PR DESCRIPTION
**Pull request by GuySartorelli**
Avoid removing translation keys that exist in yml or json but don't exist in transifex.

There was no code to merge yaml keys, so `tx pull` was always overriding the yaml content entirely.
There was code to merge json keys, but it was looking for `src/en.js` specifically, which doesn't exist. Instead, it should look for all `.json` files in the `src/` directory of each module's js lang directories.

Also removed `ksort` of the json content as per the discussion in the issue.

## Parent issue:
fixes #202

### CODE REVIEW

**Comment by emteknetnz** [comment]
I'm still seeing translations being removed in framework

image

Testing setup, using `4.5.0-beta9` to we don't accidentally publish a new tag.  This will still use the `4.x-dev` branches.

Using `master` branch

Manually update `Composer.php` to ensure `composer.config.platform.php` does interfere with installing things
```
        foreach ($customConfig as $option => $arguments) {
            if ($option == 'platform.php') continue; // <<<
```

`cow release:create -vvv 4.5.0-beta9 silverstripe/recipe-kitchen-sink`

Manually find and replace graphql `3.x-dev || 4.x-dev` to `3.x-dev` in composer files in release folder so that it doesn't fail semver check (we've previously run cow forks to handle this)

`cow release:plan -vvv 4.5.0-beta9 silverstripe/recipe-kitchen-sink`

checkout the `pulls/master/non-destructive-translations` branch

`cow release:translate -vvv --skip-fetch-tags 4.5.0-beta9 silverstripe/recipe-kitchen-sink`

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Translations still appear to be getting removed

**Comment by GuySartorelli** [comment]
@emteknetnz I am getting those results in the master branch, but not with this PR. 

Can you please confirm if the cli output has the following lines?

> [translations] Backing up local json files

A large number of "Backing up /some/path/to/module/client/lang/src/locale.json"
> [translations] Finished backing up 319 json files
> [translations] Backing up local yaml files

A large number of "Backing up /some/path/to/module/lang/locale.yml"
> [translations] Finished backing up 835 yaml files

Also I'm guessing you are getting the diff using something like `git diff HEAD^`?

**Comment by emteknetnz** [comment]
Apologies, I ran git diff while the translations were still running on kitchen-sink.  Running it after the translation commit was added, things looks much more sensible

**Review by emteknetnz — APPROVED** [review]

**Pull request merged**
