### PR TITLE
WIP API Introduce changelogs to the planner

### PR DESCRIPTION
**Pull request by ScopeyNZ**
This will compare the "prior release" to the currently checked out commit of the release project. The information is presented in a summary form, as a git log, and a GitHub compare link is provided

image

This is based off of the #143 PR branch.

WIP because I think this needs:

- [x] Don't show the changelog when asking for a prior version
- [x] Some indication of where intermediary tags exist in the given log
- [ ] I think the log is showing merge commits. Probably doesn't need that
- [x] Preferably some smarts to calculate whether the current branch of the release project already matches the previously released tag.
- [ ] Tests

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Excuse the awful commit names. I've just pushed a change that does three items from my wishlist:

> - Don't show the changelog when asking for a prior version
> - Some indication of where intermediary tags exist in the given log
> - Preferably some smarts to calculate whether the current branch of the release project already matches the previously released tag.

**Comment by unclecheese** [comment]
If and when this is merged, be sure to update release checklist (not merged yet) that refers to this PR

**Comment by ScopeyNZ** [comment]
This would be awesome to get finished. I'm sure you guys are wishing you had this right now 😅 . I'll try and put some time towards this now that I actually have a desk at home again.

**Comment by brynwhyman** [comment]
Hey @ScopeyNZ, congratulations on getting a desk ;) We're looking to put some work into Cow over the next couple of weeks. If there's specifics with this PR (or others) that you'd like some support on let us know :)

**Comment by ScopeyNZ** [comment]
I _think_ this is mostly working. Just needs tests to prove it 😅 . I would feel awful asking a different developer to write tests for my code

**Comment by Cheddam** [comment]
Here's the behaviour I'm seeing with this branch checked out when running `release:plan` against CWP 2.5.0-rc1:

image

It seems to hide all the individual modules inside the recipes. Not sure if this is expected.

<details>
<summary>
.cow.json
</summary>

```json
{
    "cwp/cwp-recipe-kitchen-sink": {
        "PriorVersion": null,
        "Version": "2.5.0-rc1",
        "Changelog": null,
        "Items": {
            "cwp/cwp-installer": {
                "PriorVersion": "2.4.0",
                "Version": "2.5.0-rc1",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "cwp/agency-extensions": {
                "PriorVersion": "2.3.0",
                "Version": "2.3.1",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "cwp/watea-theme": {
                "PriorVersion": "3.0.1",
                "Version": "3.0.1",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/controllerpolicy": {
                "PriorVersion": "2.1.0",
                "Version": "2.1.0",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/crontask": {
                "PriorVersion": "2.1.3",
                "Version": "2.1.3",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/gridfieldqueuedexport": {
                "PriorVersion": "2.3.0",
                "Version": "2.3.0",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/ldap": {
                "PriorVersion": "1.1.2",
                "Version": "1.1.2",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/recipe-content-blocks": {
                "PriorVersion": "2.4.0",
                "Version": "2.5.0-rc1",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "dnadesign/silverstripe-elemental-userforms": {
                "PriorVersion": "3.0.0",
                "Version": "3.0.0",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/textextraction": {
                "PriorVersion": "3.0.3",
                "Version": "3.0.4",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/realme": {
                "PriorVersion": "3.1.3",
                "Version": "3.1.3",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/ckan-registry": {
                "PriorVersion": "1.1.0",
                "Version": "1.1.1",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/mfa": {
                "PriorVersion": "4.0.0",
                "Version": "4.0.2",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/totp-authenticator": {
                "PriorVersion": "4.0.0",
                "Version": "4.0.0",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/webauthn-authenticator": {
                "PriorVersion": "4.0.0",
                "Version": "4.0.1",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/security-extensions": {
                "PriorVersion": "4.0.0",
                "Version": "4.0.1",
                "Changelog": null,
                "Items": [],
                "Branching": null
            },
            "silverstripe/login-forms": {
                "PriorVersion": "4.0.0",
                "Version": "4.1.0",
                "Changelog": null,
                "Items": [],
                "Branching": null
            }
        },
        "Branching": null
    }
}
```
</details>

**Comment by ScopeyNZ** [comment]
Ah right - I see what you mean. It does that if you've chosen an existing tag for a recipe. Makes sense, you can't change the versions of a recipe that's already tagged. I can't remember what the logic is in the PR for doing this - it should assume recipes need releases.

**Comment by ScopeyNZ** [comment]
I've been working on this a bit today. It is being a little dumb right now. It looks to see if the most recent prior release is also the HEAD commit. In the case of me trialing a 2.5.0-rc2 right now, it's expecting not to release any child recipes because the head commit is already tagged as the prior rc1 release. There's a few problems here to work out:

- [ ] RC1 shouldn't be counted. Any stability attributes of a release should probably be ignored for prior releases. I think that makes sense as even in the case of creating an RC2 you would still want commits showing since the last stable, not since the last RC.
- [ ] We'll need to codify the modules we want to remain in lock-step. This is a little annoying, but should be a pretty trivial addition to `.cow.json` (in cwp/cwp-recipe-kitchen-sink`
- [ ] It's not currently considering the children of recipes. Just checking that the HEAD commit is tagged is not enough. It also needs to check (recursively) that it's children all have their HEAD commits tagged with the latest prior (non unstable) release too.

I'll start working on this and commit with how far I get this afternoon.

**Comment by ScopeyNZ** [comment]
Ok I did the hardest of the three problems. The other two shouldn't be too bad, but I'm done for the day. Not sure if I'll get another chance to work on this until next weekend.

**Comment by emteknetnz** [comment]
This pull request hasn't had any activity for a while. Are you going to be doing further work on it, or would you prefer to close it now?

**Comment by ScopeyNZ** [comment]
I'm realistically never going to use this library again Steve. This is work that we would've really appreciated when I was in your team using this tool. It's entirely up to you whether you think this still has value.

I'm definitely not going to work further on this.

**Comment by Cheddam** [comment]
Totally fair. This change would reduce a lot of toil in our release process, so it's definitely valuable, but we're not in a position to dedicate time to it at the moment. I think we'll close it out for now, but will use it as a starting point for a future endeavour. Thanks for all of your work, @ScopeyNZ ❤️

**Pull request closed without merging**
